server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authorization-service
          uri: lb://authorization-service
          predicates:
            - Path=/api/authorization/**
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s